language: ruby
cache: bundler
rvm:
  - 2.1.1
before_script:
  - bundle exec rake db:create db:migrate DATABASE_URL=postgres://localhost/transitmix_test
notifications:
  webhooks: http://project-monitor.codeforamerica.org/projects/b4187edb-11eb-429e-bc0a-9eb92f6eead6/status
