source 'https://rubygems.org'

ruby '2.1.1'

gem 'airbrake', require: false
gem 'dbf'
gem 'dedent'
gem 'dotenv'
gem 'faraday', '~> 0.9'
gem 'faraday_middleware', '~> 0.9'
gem 'georuby'
gem 'grape', '~> 0.7'
gem 'moneta', '~> 0.7', github: 'invisiblefunnel/moneta', branch: 'sequel-postgres'
gem 'newrelic_rpm'
gem 'pg', '~> 0.17'
gem 'rake'
gem 'rubyzip'
gem 'ruby_kml'
gem 'sass', '~> 3.3'
gem 'sequel', '~> 4.10'
gem 'sinatra-assetpack', '~> 0.3', require: 'sinatra/assetpack'
gem 'sinatra', '~> 1.4'
gem 'uglifier', '~> 2.5'
gem 'unicorn'

group :test do
  gem 'database_cleaner'
  gem 'debugger'
  gem 'factory_girl'
  gem 'ffaker'
  gem 'rack-test'
  gem 'rspec', '~> 2.14'
  gem 'jasmine'
  gem 'webmock'
end
